config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'
  resources :users
  get "logout" => "users#destroy_login", :as => "logout"
  match "login" => "users#verify_login", :as => "login", :via => [:get,:post]
  match "password" => "users#password", :as => "password", :via => [:get,:post]
  match "reset" => "users#reset", :as => "reset", :via => [:get,:post]
  match "reset_link/:id" => "users#reset_link", :as => "reset_link", :via => [:get,:post]
  match "success_link" => "users#success_link", :as => "success_link", :via => [:get,:post]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates_presence_of :username
	validates_uniqueness_of :username

	def self.authenticate(username, password)
		user = User.find_by(username: username).try(:authenticate, password)
		if user
			user
		else
			nil
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	helper_method :current_user

	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	protect_from_forgery
	before_action :verify_login, only: [:show, :index]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to login_path, :notice => "You successfully Signed up, Please login to continue!"
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def index
		@user = User.all
	end

	def verify_login
		if !current_user
			if params[:user] && params[:user][:username] && params[:user][:password]
				@user = User.authenticate(params[:user][:username], params[:user][:password])
			end
			if @user
				session[:user_id] = @user.id
				redirect_to root_url, :notice => "Logged in!"
			else
				flash.now.alert = "Invalid email or password" if params[:user]
				render "verify_login"
			end
		end
	end

	def password
	end

	def destroy_login
		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"
	end

	private
	
	def user_params
		params.require(:user).permit(:username, :password, :confirm_password)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @projects = Project.joins(:user).left_joins(:category).order(created_at: :desc).paginate(page: params[:page], per_page: 2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=2.0,minimum-scale=1.0" />
  <title>Auctiontask</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>

  <!-- Navigation -->

  <div class="menu">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Auction</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <% if current_user %>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, :class => 'nav-link' %> 
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Login", login_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_path, :class => 'nav-link' %>
          </li>
          <% end %>
        </ul>
        <% if current_user %>
        <strong class="text-white">Hi User : <%= current_user.try(:username) %></strong>
        <% end %>
      </div>
    </nav>
  </div>
  <div class="container">
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<div class="login-wrap">
	<div class="login-html">
		<div class="login-form">
			<%= bootstrap_form_for @user, :as => :user, :url => users_path do |f| %>
			<div class="sign-in-htm">
				<div class="group">
					<%= f.text_field :username, class: "input", required: true %>
				</div>
				<div class="group">
					<%= f.password_field :password, class: "input", required: true %>
				</div>
				<div class="group">
					<%= f.submit 'Submit' , :class => "button" %>
				</div>
				<div class="hr"></div>
			</div>
			<%end%>	
		</div>
	</div>
</div>

app/views/users/verify_login.html.erb
<div class="login-wrap">
	<div class="login-html">
		<div class="login-form">
			<%= bootstrap_form_for :user, :as => :user, :url => login_path do |f| %>
			<div class="group">
				<%= f.text_field :username, class: "input", required: true %>
			</div>
			<div class="group">
				<%= f.password_field :password, class: "input", required: true %>
			</div>
			<div class="group">
				<%= f.submit 'Submit' , :class => "button" %>
			</div>
			<%end%>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th scope="col"><img src="https://img.icons8.com/wired/24/000000/numbered-list.png"></th>
			<th scope="col">Project Title</th>
			<th scope="col">category Name</th>
			<th scope="col">User Name</th>
		</tr>
	</thead>
	<tbody>
		<% @projects.each_with_index do |project,index| %>
		<tr>
			<th scope="row"><%=index+1%></th>
			<td><%= project.title%></td>
			<td><%= project.category.name %></td>
			<td><%= project.user.username %></td>
		</tr>
		<%end%>
	</tbody>
</table>
<%= will_paginate @projects %>